### ISSUE TITLE
Backdrop port

### ISSUE THREAD

**Issue by Al-Rozhkov** [drupal-fancy/view_mode_selector#14]
Thank you for your module. I use it on several sites and it works great. Now I need exactly same functionality on new [Backdrop](backdropcms.org) site, so I want to port this module to Backdrop and share with it in [Backdrop-contrib](https://github.com/backdrop-contrib).
To port your module only changing few lines of code is needed.
And I have to ask, do you guys interested in supporting a Backdrop version, or porting the module themselves?

**Comment by yannickoo** [comment]
Sorry Alexander but I'm not interested in porting this to Backdrop. I have no time available to maintain another module for another CMS :/

**Comment by Al-Rozhkov** [comment]
I understand. Just want to notify you that I did the port: https://github.com/Al-Rozhkov/view_mode_selector

Thanks again.
