### ISSUE TITLE
Drupal 8 release plan

### ISSUE THREAD

**Issue by ABaier** [drupal-fancy/view_mode_selector#15]
Hey guys, I tried the module on simpletest.me switching the view mode of a paragraph and it seems to work fine. Do you already have plans when to port the module to beta on drupal.org? upgrade path and so on … Would be really good to know about the maintainance situation for the future. Thanks in advance!

**Comment by himerus** [comment]
Wondering the same, and also create a fork to deal with some issues that have likely occurred since the last update that could use some love.

I'm in vast need of just this thing for my next project.

**Comment by yannickoo** [comment]
Sorry for the delay, are there tickets representing the issues you experienced with View Mode Selector @himerus?

I planned a new version of View Mode Selector for 03/2017 which provides much more flexibility than the current version. You can help with pull requests for the current version so far 😇

**Comment by hawkeyetwolf** [comment]
@yannickoo I'm happy to assist with any additional work needed for the release. I'll be using this in DEV form or not, but an official release would be nice :) Is the list of blockers noted anywhere?

**Comment by yannickoo** [comment]
@derekderaps sorry no, I need to check all the other issues for this module and then I will create a new issue for the refactoring issue which is the "flexibility" I have mentioned before.

**Comment by jmolivas** [comment]
@yannickoo do you have a doc with roadmap and what are the features considered for this flexibility?

**Comment by keopx** [comment]
@yannickoo any update about release plan?

**Comment by yannickoo** [comment]
Hello 👋 Unfortunately there was not enough time available for this project in the past so I couldn't working on that. The plan was to get something like [ER View Mode](https://www.drupal.org/project/er_viewmode) into this module but there is also [Paragraph View Mode](https://www.drupal.org/project/paragraph_view_mode) which also being used nowadays. 

FYI the module is getting ready for D9 and there will be an official release very soon :)
