### ISSUE TITLE
View mode selector does not work with drupal 8 paragraphs

### ISSUE THREAD

**Issue by preritmohan** [drupal-fancy/view_mode_selector#20]
When I enable the view mode after adding the view mode field to paragraph bundle and select the view mode while creating content the node content display comes empty.

The classes of view mode are wrapped perfectly. The content area is empty.

**Comment by keopx** [comment]
@preritmohan works fine for me, can you check please?

**Comment by preritmohan** [comment]
Works as designated. Thanks.
