### ISSUE TITLE
Drupal 9 Readiness fixes

### ISSUE THREAD

**Issue by meetbhanvadia** [drupal-fancy/view_mode_selector#32]
Deprecation needs to be fixed to make it compatible with Drupal 9.

**Deprecation List for 1.x-dev:**

-  view_mode_selector\src\Plugin\Field\FieldType\ViewModeSelectorItem.php	83	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0

- view_mode_selector\src\Plugin\Field\FieldWidget\ViewModeSelectorIcons.php	43	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\src\Plugin\Field\FieldWidget\ViewModeSelectorWidgetBase.php	32	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\src\Plugin\Field\FieldWidget\ViewModeSelectorWidgetBase.php	44	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\view_mode_selector.module	25	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\view_mode_selector.module	41	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\view_mode_selector.module	54	Call to deprecated method entityManager() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0.

- view_mode_selector\view_mode_selector.module	82	Call to deprecated function drupal_set_message(). Deprecated in drupal:8.5.0 and is removed from drupal:9.0.0.

- view_mode_selector\view_mode_selector.module	85	Call to deprecated function drupal_set_message(). Deprecated in drupal:8.5.0 and is removed from drupal:9.0.0.

**Comment by yannickoo** [comment]
All deprecations have been fixed, thanks for reminding 😇
