### ISSUE TITLE
PHP 7.4 warning for implode

### ISSUE THREAD

**Issue by mariacha** [drupal-fancy/view_mode_selector#35]
I'm getting this warning:
```
Deprecated function: implode(): Passing glue string after array is deprecated. Swap the parameters in Drupal\view_mode_selector\Plugin\Field\FieldWidget\ViewModeSelectorIcons->formElement() (line 144 of src/Plugin/Field/FieldWidget/ViewModeSelectorIcons.php)
```

I guess the code should be to be this to be 7.4+ compatible
```
$element['value']['#options'][$view_mode] = implode('', $output);
```

**Comment by o2-wesley** [comment]
This is a critical WSOD error for PHP8.x as this old style is no longer accepted.

Please consider opening the issue queue on drupal.org so I can share the patch to fix this. github does not accept patch files...

**Comment by mariacha** [comment]
In a pinch, you can get the patch from the open PR here: https://patch-diff.githubusercontent.com/raw/drupal-fancy/view_mode_selector/pull/36.diff

**Comment by ericdsd** [comment]
Hi , i agree with o2-wesley, creating an issue queue on drupal.org would allow this module to be contributed "the drupal way" by the community and would allow creating a new d7 release.

**Comment by ericdsd** [comment]
We also should create the same issue for 7.x version
