### ISSUE TITLE
Php 7.4 compatibility - 7.x  - implode syntax deprecation warning

### ISSUE THREAD

**Issue by ericdsd** [drupal-fancy/view_mode_selector#39]
On view_mode_selector 7.12 with php 7.4

When editing a page that contains a view_mode_selector, we get 
Deprecated function : implode(): Passing glue string after array is deprecated. Swap the parameters dans view_mode_selector_field_widget_form() (line 262 of /sites/all/modules/view_mode_selector/view_mode_selector.module).

Note this will be more critical on php 8.

**Comment by ericdsd** [comment]
`
[view_mode_selector_php-7.4_compatibility.patch.txt](https://github.com/drupal-fancy/view_mode_selector/files/9400890/view_mode_selector_php-7.4_compatibility.patch.txt)
`

Here is a patch against 7-1.2

**Comment by yannickoo** [comment]
Hey this has been fixed and there is also a new release on drupal.org – https://www.drupal.org/project/view_mode_selector
