### ISSUE TITLE
Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4

### ISSUE THREAD

**Issue by shital7mahajan** [drupal-fancy/view_mode_selector#40]
There is a PHP 8.0 compatibility warning thrown for

**FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 144 | WARNING | Passing the $glue and $pieces parameters in reverse order to
     |         | implode has been deprecated since PHP 7.4; $glue should be the
     |         | first parameter and $pieces the second
--------------------------------------------------------------------------------**

**Comment by axicdv** [comment]
[view_mode_selector_php-8_compatibility.patch.txt](https://github.com/drupal-fancy/view_mode_selector/files/9853153/view_mode_selector_php-8_compatibility.patch.txt)
`[view_mode_selector_php-8_compatibility.patch.txt](https://github.com/drupal-fancy/view_mode_selector/files/9853153/view_mode_selector_php-8_compatibility.patch.txt)`

**Comment by yannickoo** [comment]
FYI this has been fixed in the latest release which you can find on drupal.org – https://www.drupal.org/project/view_mode_selector
