### ISSUE TITLE
Offering to co-maintain the module

### ISSUE THREAD

**Issue by borisson** [drupal-fancy/view_mode_selector#42]
I would like to offer to co maintain the module, so that we can get at least the drupal 10 integration fixed.

**Comment by marcoliverteschke** [comment]
Seconded! A D10 release would be nice, as it's holding up a few projects here.

**Comment by pjoulot** [comment]
Still no D10 version :( Drupal 9 end of life is in 10 days.

**Comment by yannickoo** [comment]
Hey people! Sorry for the delay, I will take care of this during the next days 😤

**Comment by jhuhta** [comment]
Any chance to get the release out?

**Comment by PapaGrande** [comment]
@yannickoo, any updates on when a D10 version will be released? Where could you use help?

**Comment by yannickoo** [comment]
FYI the latest changes were pushed to drupal.org so you can use this module with D10 now! – https://www.drupal.org/project/view_mode_selector
