### ISSUE TITLE
WSOD with multiple view modes

### ISSUE THREAD

**Issue by erindarri** [drupal-fancy/view_mode_selector#7]
I am using view mode selector with paragraphs module. I am trying to configure my various paragraph bundles have different view modes available (for example, I'd like to have a set of paragraphs where the author can select if they want it to be two or three columns and then use a multivalue field and then another set of paragraphs where they might have four images with a multivalue field - this part is working fine when VMS is not enabled). When VMS is enabled and I am adding additional paragraphs bundles to my content, I get an ajax error:

```
Fatal error:  Cannot redeclare sortByRegionCount() (previously declared in 
/sites/all/modules/contrib/view_mode_selector/view_mode_selector.module:189) in 
/sites/all/modules/contrib/view_mode_selector/view_mode_selector.module on line 189
```

If I try to edit a page that I had created prior to implementing VMS, I get WSOD. 

Is it possible to use this with paragraphs to specify view modes for multiple paragraph bundles within a content type? It would be nice to have only a few paragraphs bundles with many display modes available.

I am going to also look into Entity VMS, as I realize I am trying to add this to multiple entities, and that might be more appropriate.

**Comment by yannickoo** [comment]
The WSOD issue has been already [fixed](https://github.com/drupal-fancy/view_mode_selector/commit/d0acaeec8079e62e2f78d8f35efe45eef18e051a) in January this year :)

I would suggest that you create a new issue for your feature request so we have this seperated.

**Comment by erindarri** [comment]
Thanks yannickoo! I see it must not be merged into the current supported version, which hasn't been updated since November of last year.  I'll check out the dev version.

**Comment by yannickoo** [comment]
Unfortunately that is true, you can see the list of all changes since November [here](https://github.com/drupal-fancy/view_mode_selector/compare/7.x-1.2...7.x-1.x).

I just had a quick discussion with @axe312ger regarding releasing a new version and we have to fix the HTML preview for view modes first and then we can safely push a new version.
